name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Maven
      # todo change?
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.6

    - name: Test
      run: >
        maven.test.failure.ignore=true
        tycho.disableP2Mirrors=true
        org.eclipse.swt.browser.UseWebKitGTK=true
        org.eclipse.swt.browser.DefaultType=WebKit
        tycho.localArtifacts=ignore
        surefire.timeout=1500
        http.nonProxyHosts=localhost
